### PR TITLE
Edited and proofread.

### PR DESCRIPTION
**Pull request by ghost**
Hello! I added and deleted words to fix awkward sentences. I changed uppercase letters to lowercase because the words after comma doesn't need to be capitalized unless it's a proper noun. I deleted the question mark in How Nix Works. I have one suggestion for the title, it would be better as Getting Started With Nix: Introduction... I didn't change it here because I don't want to screw up to code.

Overall, it's a fitting post for an introduction. Short and sweet (: there aren't really much to change which is great. I love that you used a diagram too. Great work, keep it up! In the next posts of the series, it would be great to also incorporate some GIFs if needed.

### CODE REVIEW

**Review by nasirhm — APPROVED** [review]
Looks Good to me, Thank you very much @cateroxl for Proofreading it and making this awesome PR.

Actually, I'm using [Hugo](https://gohugo.io) for building this Website and Blog.
The content for the blog is written in Markdown files (in the `hugo-devel` branch), [here](https://github.com/nasirhm/nasirhm.github.io/blob/hugo-devel/content/posts/getting-started-with-nix-introduction.md)

If you would like, we can merge this PR and I can edit the Markdown file accordingly, or If you would like to do it, we can close this PR and can you please create a new one on: `hugo-devel` and add the changes there in Markdown format.

When I'll rebuild my site for future posts, It'll have the modified changes persisted there. 

What do you think ?

P.S: Thank You :)

**Comment by nasirhm** [comment]
> Hello! I added and deleted words to fix awkward sentences. I changed uppercase letters to lowercase because the words after comma doesn't need to be capitalized unless it's a proper noun. I deleted the question mark in How Nix Works. 

Thank you for pointing out the grammatical mistakes, will make sure to not repeat them in future. 

> I have one suggestion for the title, it would be better as Getting Started With Nix: Introduction... I didn't change it here because I don't want to screw up to code.

I'll modify it in the [markdown file](https://github.com/nasirhm/nasirhm.github.io/blob/hugo-devel/content/posts/getting-started-with-nix-introduction.md).

> Overall, it's a fitting post for an introduction. Short and sweet (: there aren't really much to change which is great. I love that you used a diagram too. Great work, keep it up! In the next posts of the series, it would be great to also incorporate some GIFs if needed.

Point taken, Will add some Gifs regarding Nix for future posts to increase the engagement aspect of it.

**Comment by nasirhm** [comment]
I'm merging it and we can have the changes for Markdown in another PR, Thank you very much @cateroxl for working on it and proof reading it. :)

**Comment by ghost** [comment]
On it now (:

**Pull request merged**
